In [64]:
import pandas as pd
import pyarrow

In [14]:
url = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv'

In [ ]:
df.head()

In [18]:
#df = pd.read_csv(url)


dtype = {
"LocationID": "Int64",
"Borough": "string",
"Zone": "string",
"service_zone": "string"
}


df = pd.read_csv(
    url,
    dtype=dtype
)

In [19]:
df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [20]:
df

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                       NV         <NA>
264         265        Unknown                     <NA>         <NA>

[265 rows x 4 columns]

In [21]:
len(df)

265

In [32]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://postgres:postgres@localhost:5433/ny_taxi"
)

In [33]:
df.head(n=0).to_sql(name="green_taxi_data", con=engine, if_exists='replace')

0

In [34]:
df.head(0)

Empty DataFrame
Columns: [LocationID, Borough, Zone, service_zone]
Index: []

In [35]:
print(pd.io.sql.get_schema(df, name='green_taxi_data', con=engine))

CREATE TABLE green_taxi_data (
	"LocationID" BIGINT,
	"Borough" TEXT,
	"Zone" TEXT,
	service_zone TEXT
)

In [54]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    iterator=True,
    chunksize=100
)

In [55]:
from tqdm.auto import tqdm

In [57]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='green_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]

In [61]:
parquet_url = 'https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet'

In [66]:
df = pd.read_parquet(parquet_url, engine='pyarrow')

In [67]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [68]:
len(df)

46912

In [71]:
dtype = { 
    "VendorID": "Int64", 
    "passenger_count": "Int64", 
    "trip_distance": "float64", 
    "RatecodeID": "Int64", 
    "store_and_fwd_flag": "string", 
    "PULocationID": "Int64", 
    "DOLocationID": "Int64", 
    "payment_type": "Int64", 
    "fare_amount": "float64", 
    "extra": "float64", 
    "mta_tax": "float64", 
    "tip_amount": "float64", 
    "tolls_amount": "float64", 
    "improvement_surcharge": "float64", 
    "total_amount": "float64", 
    "congestion_surcharge": "float64" 
}
parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

In [79]:
# df = pd.read_parquet(
#     parquet_url,
#     dtype=dtype,
#     parse_dates=parse_dates

# )

df = pd.read_parquet(parquet_url)

df = df.astype(dtype)

In [80]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1,74,42,1,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1,74,42,2,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1,83,160,1,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1,166,127,1,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1,166,262,1,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1,1.0,2.75,0.0

In [81]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://postgres:postgres@localhost:5433/ny_taxi"
)

In [82]:
df.head(n=0).to_sql(name="green_taxi_data", con=engine, if_exists='replace')

0

In [83]:
df.head(0)

Empty DataFrame
Columns: [VendorID, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, RatecodeID, PULocationID, DOLocationID, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type, congestion_surcharge, cbd_congestion_fee]
Index: []

[0 rows x 21 columns]

In [84]:
print(pd.io.sql.get_schema(df, name='green_taxi_data', con=engine))

CREATE TABLE green_taxi_data (
	"VendorID" BIGINT,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" BIGINT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type BIGINT,
	trip_type FLOAT(53),
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)

In [94]:
# df_iter = pd.read_parquet(
#     parquet_url,
#     dtype=dtype,
#     iterator=True,
#     chunksize=10000
# )



# import pyarrow
# import pyarrow.parquet as pq

# print(pyarrow.__version__) # 13.0.0

# path = "pa" # path to your parquet file
# batch_size = 10_000 # number of rows to load in memory

# parquet_file = pq.ParquetFile(path)

# for batch in parquet_file.iter_batches(batch_size=batch_size):
#     # process your batch
    

import pyarrow
import pyarrow.parquet as pq
from pathlib import Path
import requests

print(pyarrow.__version__)  # 13.0.0

parquet_url = "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet"

path = Path("green_tripdata_2025-11.parquet")
batch_size = 10_000

# download once
if not path.exists():
    response = requests.get(parquet_url)
    response.raise_for_status()
    path.write_bytes(response.content)

parquet_file = pq.ParquetFile(path)

for batch in parquet_file.iter_batches(batch_size=batch_size):
    df_batch = batch.to_pandas()
    # process df_batch

23.0.0

In [95]:
from tqdm.auto import tqdm

In [96]:
import pyarrow.parquet as pq

table_name = "green_tripdata"

parquet_file = pq.ParquetFile(path)

for batch in parquet_file.iter_batches(batch_size=10_000):
    df_batch = batch.to_pandas()

    df_batch.to_sql(
        table_name,
        engine,
        if_exists="append",
        index=False,
        method="multi"
    )